### ISSUE TITLE
Not accepted by google calendar

### ISSUE THREAD

**Issue by pcoenen** [MidasLamb/CSSchedule#32]
The following URL is not allowed by google Calendar

https://csschedule.xyz/calendar/?&courses[]=H01F2AN&courses[]=G0Q57AN&courses[]=H01L1AN&courses[]=H0N08AE&courses[]=H04I4AN&courses[]=G0B23AN&courses[]=H0N05AN&courses[]=H0N05AE&courses[]=H09B5BN&courses[]=H07Z9BE&courses[]=H07Z9BN&courses[]=H02C1AE&courses[]=H02A8AE&courses[]=H04K5AE&courses[]=H04K5AN&courses[]=H02C6AE&courses[]=H02C6AN&courses[]=H02C3AE

**Comment by MidasLamb** [comment]
Seems to be because google has a character limit on the url you wish to import: [source](https://productforums.google.com/forum/#!topic/calendar/VlpFlVnKrGw;context-place=topicsearchin/calendar/authorid$3AAPn2wQcVDcjpSfqOgoxxA22jhK_-MZPHvkuIrat3jGkPS5DjnuI9M2hmiszJlZousQp8Wnf242e6%7Csort:date%7Cspell:false)
